services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Connexion à ta base Supabase :
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: db.ezvozlewtryujnlioyxj.supabase.co   # ← ce que tu as copié
      - key: DB_POSTGRESDB_PORT
        value: "5432"                               # ← ce que tu as copié
      - key: DB_POSTGRESDB_DATABASE
        value: postgres                             # ← ce que tu as copié
      - key: DB_POSTGRESDB_USER
        value: postgres                             # ← ce que tu as copié
      - key: DB_POSTGRESDB_PASSWORD
        value: far%8UvTP-Ps$7@          # ← celui que tu as réinitialisé

      # Basic Auth pour sécuriser l’UI :
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: salah110392                         # ← choisis le nom d’utilisateur
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Bulbizarre&110392           # ← choisis un mot de passe robuste

      # URL publique et webhooks :
      - key: N8N_HOST
        value: n8n-service.onrender-1vjn.com             # ← remplace par le nom de ton service Render
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com/

