services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      # 1) Clé d’encryption (générée automatiquement une fois, ne surtout pas régénérer)
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
        
      # == Ajoute cette ligne ==
      - key: N8N_PROXY_HOPS
        value: "1"

      # 2) Connexion à Supabase
      - key: DB_TYPE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value:    # ← ton Host Supabase
      - key: DB_POSTGRESDB_PORT
        value: "5432"                              # ← ton Port Supabase
      - key: DB_POSTGRESDB_DATABASE
        value: postgres                             # ← ta DB Supabase
      - key: DB_POSTGRESDB_USER
        value: postgres                             # ← ton User Supabase
      - key: DB_POSTGRESDB_PASSWORD
        value: far%8UvTP-Ps$7@          # ← ton Password Supabase

      # 3) Création automatique du compte “owner”
      - key: N8N_SETUP_OWNER_EMAIL
        value: salaheddine.benbouazza@gmail.com                    # ← l’email que tu veux pour l’admin
      - key: N8N_SETUP_OWNER_FIRST_NAME
        value: Salaheddine                          # ← ton prénom
      - key: N8N_SETUP_OWNER_LAST_NAME
        value: Ben Bouazza                              # ← ton nom
      - key: N8N_SETUP_OWNER_PASSWORD
        value: Bulbizarre&13002               # ← mot de passe admin, 8+ car., 1Maj, 1 chiffre

      # 4) Protection HTTP Basic Auth (popup navigateur)
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: salah110392                           # ← identifiant Basic Auth
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Bulbizarre&11039213          # ← mot de passe Basic Auth

      # 5) URLs publiques & webhooks
      - key: N8N_HOST
        value: n8n-service-1vjn.onrender.com     # ← ton hostname Render
      - key: N8N_PROTOCOL
        value: https
      - key: WEBHOOK_URL
        value: https://n8n-service-1vjn.onrender.com/
