# n8n + Supabase (Transaction Pooler IPv4-compatible)

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # Connexion à Supabase via le pooler (IPv4 compatible)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: postgres.eu-west-1.supabase.com  # Hôte du pooler partagé
      - key: DB_POSTGRESDB_PORT
        value: "6543"
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.ezvozlewtryujnlioyxj  # Récupéré de l’URI du pooler
      - key: DB_POSTGRESDB_PASSWORD
        value: mLL6I35R1Wv8sYjn  # Ton mot de passe Supabase


