# n8n + Supabase (Transaction Pooler, IPv4-compatible)

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # Configuration de la base Supabase via le transaction pooler
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: db.ezvozlewtryujnlioyxj.supabase.co  # ← Hôte réel
      - key: DB_POSTGRESDB_PORT
        value: "6543"  # ← Port du transaction pooler
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_USER
        value: postgres.ezvozlewtryujnlioyxj  # ← Utilisateur du pooler
      - key: DB_POSTGRESDB_PASSWORD
        value: mLL6I35R1Wv8sYjn  # ← Ton mot de passe Supabase



