# Use this Blueprint to deploy n8n on Render as a web
# service that uses a Postgres database to store
# workflow data.

services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest

    envVars:
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: postgres
      - key: DB_POSTGRESDB_HOST
        value: db.ezvozlewtryujnlioyxj.supabase.co
      - key: DB_POSTGRESDB_PASSWORD
        value: mLL6I35R1Wv8sYjn
      - key: DB_POSTGRESDB_USER
        value: postgres
      - key: DB_POSTGRESDB_PORT
        value: "5432"

